### ISSUE TITLE
Set up Python, FastAPI for backend server

### ISSUE THREAD

**Issue by yurikahirata** [WG-CC/transitiontoolkit-backend#2]
# Problem
Installing Python using the FastAPI framework. Creating a requirements.txt file and a makefile.

Read the FastAPI documentation:
https://fastapi.tiangolo.com/tutorial/

# Success
Running the makefile commands on Windows and Mac.

### Requirements

- [ ] Create new branch from dev (name/issue Ex: yurika/setup-python)
- [ ] Install Python
- [ ] Install FastAPI
- [ ] Create a makefile with the following commands (should work with Windows and Mac)
  - [ ] Create virtual environment
  - [ ] Installing dependencies
  - [ ] Running the server
- [ ] Create a requirements.txt
- [ ] Update backend repository README to include python installation documentation under Prerequisites, and update Install Dependencies section

**Comment by NabbeunNabi** [comment]
The PR that is linked to this ticket is https://github.com/WG-CC/transitiontoolkit-backend/pull/5
