### ISSUE TITLE
NoSQL database research

### ISSUE THREAD

**Issue by yurikahirata** [WG-CC/transitiontoolkit-backend#4]
# Problem
Research NoSQL databases and make a recommendation for the best one for the project. Explain reasons why.
Consider security as we are storing sensitive information.

# Success
A recommendation for a NoSQL database to utilize for this project.

### Requirements

- [ ] Research NoSQL databases
- [ ] Make a recommendation for which database to use

**Comment by Anissa3005** [comment]
https://art049.github.io/odmantic/

https://www.mongodb.com/atlas/database

**Comment by vyridian17** [comment]
Done: MongoDB Atlas
